// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ContainerLoad: typeof import('./components/ContainerLoad/ContainerLoad.vue')['default']
    HomeLeft: typeof import('./components/HomeLeft.vue')['default']
    'HomeLeft copy': typeof import('./components/HomeLeft copy.vue')['default']
    HomeMiddle: typeof import('./components/HomeMiddle.vue')['default']
    'HomeMiddle copy': typeof import('./components/HomeMiddle copy.vue')['default']
    HomeRight: typeof import('./components/HomeRight.vue')['default']
    'HomeRight copy': typeof import('./components/HomeRight copy.vue')['default']
    HomeRight1: typeof import('./components/HomeRight1.vue')['default']
    'HomeRight1 copy': typeof import('./components/HomeRight1 copy.vue')['default']
    HomeRight2: typeof import('./components/HomeRight2.vue')['default']
    'HomeRight2 copy': typeof import('./components/HomeRight2 copy.vue')['default']
    HomeRight3: typeof import('./components/HomeRight3.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    ScaleContainer: typeof import('./components/ScaleContainer/ScaleContainer.vue')['default']
    TweenNumber: typeof import('./components/TweenNumber/TweenNumber.vue')['default']
    VueEcharts: typeof import('./components/VueEcharts/VueEcharts.vue')['default']
  }
}

export { }
