// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ContainerLoad: typeof import('./components/ContainerLoad/ContainerLoad.vue')['default']
    ElProgress: typeof import('element-ui/lib/progress')['default']
    HomeLeft: typeof import('./components/HomeLeft.vue')['default']
    HomeLeftItem1: typeof import('./components/HomeLeftItem1.vue')['default']
    HomeLeftItem2: typeof import('./components/HomeLeftItem2.vue')['default']
    HomeLeftItem3: typeof import('./components/HomeLeftItem3.vue')['default']
    'HomeLeftItem3 copy': typeof import('./components/HomeLeftItem3 copy.vue')['default']
    HomeLeftItem3Highcharts: typeof import('./components/HomeLeftItem3Highcharts.vue')['default']
    HomeMiddle: typeof import('./components/HomeMiddle.vue')['default']
    HomeRight1: typeof import('./components/HomeRight1.vue')['default']
    HomeRight2: typeof import('./components/HomeRight2.vue')['default']
    'HomeRight2 copy': typeof import('./components/HomeRight2 copy.vue')['default']
    HomeRight2Item1: typeof import('./components/HomeRight2Item1.vue')['default']
    HomeRight2Item2: typeof import('./components/HomeRight2Item2.vue')['default']
    HomeRight2Item3: typeof import('./components/HomeRight2Item3.vue')['default']
    HomeRight2Item4: typeof import('./components/HomeRight2Item4.vue')['default']
    HomeRight3: typeof import('./components/HomeRight3.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    ScaleContainer: typeof import('./components/ScaleContainer/ScaleContainer.vue')['default']
    TweenNumber: typeof import('./components/TweenNumber/TweenNumber.vue')['default']
    VueEcharts: typeof import('./components/VueEcharts/VueEcharts.vue')['default']
  }
}

export { }
